"""Static types and Runtime-safe type protocols for IOCE Java classes.

Fancy dual-type strategy:
- During TYPE_CHECKING: Uses generated .pyi stubs for full IDE autocomplete
- At runtime: Uses Protocol types that are safe (no Java import dependencies)

Import from this module and automatically get the correct types in each context.
"""

from typing import Protocol, runtime_checkable, Any, TYPE_CHECKING

if TYPE_CHECKING:
    # Import generated stubs for IDE autocomplete during type checking
    from gov.cms.oce.model.external import OceClaim as OceClaim
    from gov.cms.oce.model.external import OceLineItem as OceLineItem
    from gov.cms.oce.model.external import OceDiagnosisCode as OceDiagnosisCode
    from gov.cms.oce.model.external import OceHcpcsModifier as OceHcpcsModifier
    from gov.cms.oce.model.external import OceValueCode as OceValueCode
    from gov.cms.oce.model.external import (
        OceProcessingInformation as OceProcessingInformation,
    )
    from gov.cms.oce.model.external import OceClaimFactory as OceClaimFactory
    from gov.cms.oce import IoceComponent as IoceComponent
    from gov.cms.oce import IoceClaim as IoceClaim
else:
    # Protocol types for runtime use
    # runtime_checkable decorator allows isinstance checks at runtime

    @runtime_checkable
    class OceProcessingInformation(Protocol):
        """Protocol for OceProcessingInformation"""

        def getClaimId(self) -> str: ...
        def getCommentData(self) -> str: ...
        def getDebugFlag(self) -> str: ...
        def getInternalVersion(self) -> int: ...
        def getLinesProcessed(self) -> int: ...
        def getReturnCode(self) -> int: ...
        def getTimeEnded(self) -> int: ...
        def getTimeStarted(self) -> int: ...
        def getVersion(self) -> str: ...
        def setClaimId(self, claim_id: str) -> None: ...
        def setCommentData(self, comment: str) -> None: ...
        def setDebugFlag(self, flag: str) -> None: ...

    @runtime_checkable
    class OceDiagnosisCode(Protocol):
        """Protocol for OceDiagnosisCode"""

        def getDiagnosis(self) -> str: ...
        def getEditList(self) -> Any: ...  # java.util.List[str] at runtime
        def getPresentOnAdmission(self) -> str: ...
        def setDiagnosis(self, code: str) -> None: ...
        def setPresentOnAdmission(self, poa: str) -> None: ...

    @runtime_checkable
    class OceHcpcsModifier(Protocol):
        """Protocol for OceHcpcsModifier"""

        def getEditList(self) -> Any: ...  # java.util.List[str] at runtime
        def getHcpcsModifier(self) -> str: ...
        def setHcpcsModifier(self, modifier: str) -> None: ...

    @runtime_checkable
    class OceValueCode(Protocol):
        """Protocol for OceValueCode"""

        def getCode(self) -> str: ...
        def getValue(self) -> str: ...
        def setCode(self, code: str) -> None: ...
        def setValue(self, value: str) -> None: ...

    @runtime_checkable
    class OceLineItem(Protocol):
        """Protocol for OceLineItem"""

        def addContractorEditBypass(self, bypass: str) -> None: ...
        def addHcpcsModifierInput(self, modifier: str) -> None: ...
        def getActionFlagInput(self) -> str: ...
        def getActionFlagOutput(self) -> str: ...
        def getCharge(self) -> str: ...
        def getCompositeAdjustmentFlag(self) -> str: ...
        def getContractorApc(self) -> str: ...
        def getContractorDiscountingFormula(self) -> str: ...
        def getContractorEditBypassList(self) -> Any: ...  # java.util.List[str]
        def getContractorEditBypassListLength(self) -> int: ...
        def getContractorPackagingFlag(self) -> str: ...
        def getContractorPaymentAdjustmentFlag01(self) -> str: ...
        def getContractorPaymentAdjustmentFlag02(self) -> str: ...
        def getContractorPaymentIndicator(self) -> str: ...
        def getContractorPaymentMethodFlag(self) -> str: ...
        def getContractorRejectionDenialFlag(self) -> str: ...
        def getContractorStatusIndicator(self) -> str: ...
        def getDiscountingFormula(self) -> str: ...
        def getHcpcs(self) -> str: ...
        def getHcpcsApc(self) -> str: ...
        def getHcpcsEditList(self) -> Any: ...  # java.util.List[str]
        def getHcpcsModifierInputList(
            self,
        ) -> Any: ...  # java.util.List[OceHcpcsModifier]
        def getHcpcsModifierInputListLength(self) -> int: ...
        def getHcpcsModifierOutputList(
            self,
        ) -> Any: ...  # java.util.List[OceHcpcsModifier]
        def getPackagingFlag(self) -> str: ...
        def getPaymentAdjustmentFlag01(self) -> str: ...
        def getPaymentAdjustmentFlag02(self) -> str: ...
        def getPaymentApc(self) -> str: ...
        def getPaymentIndicator(self) -> str: ...
        def getPaymentMethodFlag(self) -> str: ...
        def getRejectionDenialFlag(self) -> str: ...
        def getRevenueCode(self) -> str: ...
        def getRevenueEditList(self) -> Any: ...  # java.util.List[str]
        def getServiceDate(self) -> str: ...
        def getServiceDateEditList(self) -> Any: ...  # java.util.List[str]
        def getStatusIndicator(self) -> str: ...
        def getUnitsInput(self) -> str: ...
        def getUnitsOutput(self) -> str: ...
        def setActionFlagInput(self, flag: str) -> None: ...
        def setCharge(self, charge: str) -> None: ...
        def setContractorApc(self, apc: str) -> None: ...
        def setContractorDiscountingFormula(self, formula: str) -> None: ...
        def setContractorEditBypass(self, index: int, bypass: str) -> None: ...
        def setContractorPackagingFlag(self, flag: str) -> None: ...
        def setContractorPaymentAdjustmentFlag01(self, flag: str) -> None: ...
        def setContractorPaymentAdjustmentFlag02(self, flag: str) -> None: ...
        def setContractorPaymentIndicator(self, indicator: str) -> None: ...
        def setContractorPaymentMethodFlag(self, flag: str) -> None: ...
        def setContractorRejectionDenialFlag(self, flag: str) -> None: ...
        def setContractorStatusIndicator(self, indicator: str) -> None: ...
        def setHcpcs(self, hcpcs: str) -> None: ...
        def setHcpcsModifierInput(self, index: int, modifier: str) -> None: ...
        def setRevenueCode(self, code: str) -> None: ...
        def setServiceDate(self, date: str) -> None: ...
        def setUnitsInput(self, units: str) -> None: ...

    @runtime_checkable
    class OceClaim(Protocol):
        """Protocol for OceClaim"""

        def addConditionCodeInput(self, code: str) -> None: ...
        def addLineItem(self, line_item: OceLineItem) -> None: ...
        def addOccurrenceCodeInput(self, code: str) -> None: ...
        def addReasonForVisitDiagnosisCode(self, dx: OceDiagnosisCode) -> None: ...
        def addSecondaryDiagnosisCode(self, dx: OceDiagnosisCode) -> None: ...
        def addValueCodeInput(self, value_code: OceValueCode) -> None: ...
        def getAge(self) -> str: ...
        def getApcReturnBufferFlag(self) -> str: ...
        def getBillType(self) -> str: ...
        def getClaimDenialDisposition(self) -> str: ...
        def getClaimDenialEditList(self) -> Any: ...  # java.util.List[str]
        def getClaimDisposition(self) -> str: ...
        def getClaimId(self) -> str: ...
        def getClaimProcessedFlag(self) -> str: ...
        def getClaimRejectionDisposition(self) -> str: ...
        def getClaimRejectionEditList(self) -> Any: ...  # java.util.List[str]
        def getClaimReturnToProviderDisposition(self) -> str: ...
        def getClaimReturnToProviderEditList(self) -> Any: ...  # java.util.List[str]
        def getClaimSuspensionDisposition(self) -> str: ...
        def getClaimSuspensionEditList(self) -> Any: ...  # java.util.List[str]
        def getCmsCertificationNumber(self) -> str: ...
        def getConditionCodeInputList(self) -> Any: ...  # java.util.List[str]
        def getConditionCodeInputListLength(self) -> int: ...
        def getConditionCodeOutputList(self) -> Any: ...  # java.util.List[str]
        def getDateEnded(self) -> str: ...
        def getDateStarted(self) -> str: ...
        def getLineDenialDisposition(self) -> str: ...
        def getLineDenialEditList(self) -> Any: ...  # java.util.List[str]
        def getLineItemList(self) -> Any: ...  # java.util.List[OceLineItem]
        def getLineItemListLength(self) -> int: ...
        def getLineRejectionDisposition(self) -> str: ...
        def getLineRejectionEditList(self) -> Any: ...  # java.util.List[str]
        def getNationalProviderId(self) -> str: ...
        def getNoppsBillFlag(self) -> str: ...
        def getOccurrenceCodeInputList(self) -> Any: ...  # java.util.List[str]
        def getOccurrenceCodeInputListLength(self) -> int: ...
        def getOppsFlag(self) -> str: ...
        def getPatientStatus(self) -> str: ...
        def getPrincipalDiagnosisCode(self) -> OceDiagnosisCode: ...
        def getProcessingInformation(self) -> OceProcessingInformation: ...
        def getReasonForVisitDiagnosisCodeList(
            self,
        ) -> Any: ...  # java.util.List[OceDiagnosisCode]
        def getReasonForVisitDiagnosisCodeListLength(self) -> int: ...
        def getReceiptDate(self) -> str: ...
        def getSecondaryDiagnosisCodeList(
            self,
        ) -> Any: ...  # java.util.List[OceDiagnosisCode]
        def getSecondaryDiagnosisCodeListLength(self) -> int: ...
        def getSex(self) -> str: ...
        def getValueCodeInputList(self) -> Any: ...  # java.util.List[OceValueCode]
        def getValueCodeInputListLength(self) -> int: ...
        def getValueCodeOutputList(self) -> Any: ...  # java.util.List[OceValueCode]
        def getVersion(self) -> str: ...
        def setAge(self, age: str) -> None: ...
        def setBillType(self, bill_type: str) -> None: ...
        def setClaimId(self, claim_id: str) -> None: ...
        def setCmsCertificationNumber(self, cert_num: str) -> None: ...
        def setConditionCodeInput(self, index: int, code: str) -> None: ...
        def setDateEnded(self, date: str) -> None: ...
        def setDateStarted(self, date: str) -> None: ...
        def setLineItem(self, index: int, line_item: OceLineItem) -> None: ...
        def setNationalProviderId(self, npi: str) -> None: ...
        def setOccurrenceCodeInput(self, index: int, code: str) -> None: ...
        def setOppsFlag(self, flag: str) -> None: ...
        def setPatientStatus(self, status: str) -> None: ...
        def setPrincipalDiagnosisCode(self, dx: OceDiagnosisCode) -> None: ...
        def setReasonForVisitDiagnosisCode(
            self, index: int, dx: OceDiagnosisCode
        ) -> None: ...
        def setReceiptDate(self, date: str) -> None: ...
        def setSecondaryDiagnosisCode(
            self, index: int, dx: OceDiagnosisCode
        ) -> None: ...
        def setSex(self, sex: str) -> None: ...
        def setValueCodeInput(self, index: int, value_code: OceValueCode) -> None: ...
        def toString(self) -> str: ...

    @runtime_checkable
    class OceClaimFactory(Protocol):
        """Protocol for OceClaimFactory"""

        def createClaim(self) -> OceClaim: ...
        def createDiagnosisCode(
            self, code: str = "", poa: str = ""
        ) -> OceDiagnosisCode: ...
        def createHcpcsModifier(self, modifier: str = "") -> OceHcpcsModifier: ...
        def createLineItem(self) -> OceLineItem: ...
        def createValueCode(self, code: str = "", value: str = "") -> OceValueCode: ...

        @staticmethod
        def getInstance() -> "OceClaimFactory": ...

    @runtime_checkable
    class IoceClaim(Protocol):
        """Protocol for IoceClaim"""

        def __init__(self, claim: OceClaim) -> None: ...
        def getClaimId(self) -> str: ...
        def getModel(self) -> OceClaim: ...
        def setClaimId(self, claim_id: str) -> None: ...

    @runtime_checkable
    class IoceComponent(Protocol):
        """Protocol for IoceComponent"""

        def __init__(self) -> None: ...
        def close(self) -> None: ...
        def getApcDescription(self, apc: str, version: int) -> str: ...
        def getClaimDispositionDescription(
            self, disposition_type: str, version: int
        ) -> str: ...
        def getClaimDispositionValueDescription(
            self, disposition_type: str, disposition_value: str, version: int
        ) -> str: ...
        def getClaimProcessedFlagDescription(self, flag: str, version: int) -> str: ...
        def getDiagnosisDescription(self, code: str, version: int) -> str: ...
        def getDiscountFormulaDescription(self, formula: str, version: int) -> str: ...
        def getEditDescription(self, edit: str, version: int) -> str: ...
        def getEditDispositionDescription(
            self, disposition: str, version: int
        ) -> str: ...
        def getErrorDescription(self, error: str, version: int) -> str: ...
        def getHcpcsDescription(self, hcpcs: str, version: int) -> str: ...
        def getHcpcsModifierDescription(self, modifier: str, version: int) -> str: ...
        def getLatestApcDescription(self, apc: str) -> str: ...
        def getLatestClaimDispositionDescription(
            self, disposition_type: str
        ) -> str: ...
        def getLatestClaimDispositionValueDescription(
            self, disposition_type: str, disposition_value: str
        ) -> str: ...
        def getLatestClaimProcessedFlagDescription(self, flag: str) -> str: ...
        def getLatestDiagnosisDescription(self, code: str) -> str: ...
        def getLatestDiscountFormulaDescription(self, formula: str) -> str: ...
        def getLatestEditDescription(self, edit: str) -> str: ...
        def getLatestEditDispositionDescription(self, disposition: str) -> str: ...
        def getLatestErrorDescription(self, error: str) -> str: ...
        def getLatestHcpcsDescription(self, hcpcs: str) -> str: ...
        def getLatestHcpcsModifierDescription(self, modifier: str) -> str: ...
        def getLatestLineItemActionFlagDescription(self, flag: str) -> str: ...
        def getLatestLineItemRejectionDenialFlagDescription(self, flag: str) -> str: ...
        def getLatestPackagingFlagDescription(self, flag: str) -> str: ...
        def getLatestPaymentAdjustmentFlagDescription(self, flag: str) -> str: ...
        def getLatestPaymentIndicatorDescription(self, indicator: str) -> str: ...
        def getLatestPaymentMethodFlagDescription(self, flag: str) -> str: ...
        def getLatestRevenueCodeDescription(self, code: str) -> str: ...
        def getLatestStatusIndicatorDescription(self, indicator: str) -> str: ...
        def getLatestValueCodeDescription(self, code: str) -> str: ...
        def getLineItemActionFlagDescription(self, flag: str, version: int) -> str: ...
        def getLineItemRejectionDenialFlagDescription(
            self, flag: str, version: int
        ) -> str: ...
        def getPackagingFlagDescription(self, flag: str, version: int) -> str: ...
        def getPaymentAdjustmentFlagDescription(
            self, flag: str, version: int
        ) -> str: ...
        def getPaymentIndicatorDescription(
            self, indicator: str, version: int
        ) -> str: ...
        def getPaymentMethodFlagDescription(self, flag: str, version: int) -> str: ...
        def getRevenueCodeDescription(self, code: str, version: int) -> str: ...
        def getStatusIndicatorDescription(
            self, indicator: str, version: int
        ) -> str: ...
        def getValueCodeDescription(self, code: str, version: int) -> str: ...
        def process(self, claim: IoceClaim) -> None: ...
        def reconfigure(self, runtime_option: Any) -> None: ...
